version: '3'
services:
  mongodb:
    container_name: convert-currency-api
    image: mongo:4
    restart: always
    volumes:
      - ./db:/data/db
    ports:
      - '27017:27017'
  api:
    container_name: api-convert-currency
    build: .
    image: convert-currency-api
    command: npm start
    volumes:
      - ./dist:/usr/src/convert-currency-api/dist
    ports:
      - '3037:3037'
    env_file:
      - .env
    links:
      - mongodb